### ISSUE TITLE
Document exception handling

### ISSUE THREAD

**Issue by m3taphysics** [getbaseline/Baseline.Filesystem#296]
It would be simpler to allow the caller to manage any exceptions thrown if the Baseline.Filesystem cannot do anything specific with the exception. Currently baseline appears to wrap all exceptions meaning the caller has to unwrap them unnecessarily. A specific example where this can cause a problem is below:

```
try {
 fileManager.ReadAsStreamAsync();
}
catch (OperationCancelledException e) {
 //do nothing
}

//cancellation is never caught because you would need to unrwap **StoreAdapterOperationException** 

```

https://github.com/getbaseline/Baseline.Filesystem/blob/main/src/Baseline.Filesystem/Internal/Extensions/ExternalExceptionExtensions.cs

**Comment by lsymds** [comment]
The aim of this was to prevent the exposure of adapter related exceptions and also provide a common exception that could be caught that would encapsulate ANY possible exception that could be thrown.

You can either unwrap the exception as you said or add an exception filter (https://learn.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers) to make it nicer. 

```csharp
try
{
    await fileManager.ReadAsStreamAsync();
}
catch (StoreAdapterOperationException e) when (e.InnerException is OperationCancelledException oex)
{
    // Do nothing.
}
```

**Comment by lsymds** [comment]
Added some documentation to make it clearer: https://docs.getbaseline.net/filesystem/basic-usage.html#exception-handling
